//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimentos
    {
        public long codAlimento { get; set; }
        public string nomeAlimento { get; set; }
        public Nullable<decimal> qtd { get; set; }
        public Nullable<decimal> kcal { get; set; }
        public Nullable<decimal> prot { get; set; }
        public Nullable<decimal> carbo { get; set; }
        public Nullable<decimal> lipidio { get; set; }
        public string nomeTabela { get; set; }
    }
}
