//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC2
{
    using System;
    using System.Collections.Generic;
    
    public partial class MedidaCaseira
    {
        public long ID { get; set; }
        public string descricao { get; set; }
        public Nullable<double> qtd { get; set; }
        public Nullable<long> codAlimento { get; set; }
    
        public virtual Alimentos Alimentos { get; set; }
    }
}
