//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriEz.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Agenda
    {
        public long ID { get; set; }
        public string paciente { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<bool> retorno { get; set; }
        public Nullable<bool> atendido { get; set; }
        public Nullable<int> Cancelado { get; set; }
        public string usuarioResp { get; set; }
    }
}
