//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriEz.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alimentos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Alimentos()
        {
            this.Cardapio = new HashSet<Cardapio>();
            this.MedidaCaseira = new HashSet<MedidaCaseira>();
        }
    
        public long codAlimento { get; set; }
        public string nomeAlimento { get; set; }
        public Nullable<double> qtd { get; set; }
        public Nullable<double> kcal { get; set; }
        public Nullable<double> prot { get; set; }
        public Nullable<double> carbo { get; set; }
        public Nullable<double> lipidio { get; set; }
        public string nomeTabela { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cardapio> Cardapio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MedidaCaseira> MedidaCaseira { get; set; }
    }
}
