//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriEz.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnamneseConfig
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AnamneseConfig()
        {
            this.AnamnesePaciente = new HashSet<AnamnesePaciente>();
        }
    
        public string Template { get; set; }
        public string Texto { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnamnesePaciente> AnamnesePaciente { get; set; }
    }
}
