//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriEz.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cardapio
    {
        public long ID { get; set; }
        public Nullable<long> codPaciente { get; set; }
        public Nullable<long> codAlimento { get; set; }
        public Nullable<double> medidaCaseiraQtde { get; set; }
        public string Refeicao { get; set; }
        public Nullable<double> kcal { get; set; }
        public string data { get; set; }
        public string usuarioResp { get; set; }
        public string obs { get; set; }
    
        public virtual Alimentos Alimentos { get; set; }
        public virtual Paciente Paciente { get; set; }
    }
}
