//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TCC2.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class ConfiguracoesUsuarios
    {
        public long ID { get; set; }
        public Nullable<long> codPaciente { get; set; }
        public string diaSemana { get; set; }
        public string horaInicio { get; set; }
        public string horaFim { get; set; }
    
        public virtual Paciente Paciente { get; set; }
    }
}
