//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NutriEz.Banco_de_Dados
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissao
    {
        public long ID { get; set; }
        public string usuario { get; set; }
        public string programa { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
